# DO NOT COMMIT THIS FILE TO GIT
# This is a template for creating secrets
# Use kubectl create secret or external secrets management

apiVersion: v1
kind: Secret
metadata:
  name: aumbit-secrets
  namespace: default
type: Opaque
stringData:
  # PostgreSQL connection string for production
  # Format: postgresql://username:password@host:port/database
  database-url: "postgresql://aumbit_user:CHANGE_ME@postgres-host:5432/aumbit_prod"

  # Generate a secure secret: openssl rand -hex 32
  nextauth-secret: "CHANGE_ME_TO_32_CHARACTER_SECRET"

  # AWS credentials (if not using IRSA)
  # aws-access-key-id: "CHANGE_ME"
  # aws-secret-access-key: "CHANGE_ME"